### PR TITLE
Sen ddlog

### PR DESCRIPTION
**Pull request by senwu**
1. Add ddlog version genomics application
2. Support view

TODOs:
1. Delete id column in schema(it's unnecessary now).
2. Mindbender has some problems with multiple keys, need modify ddlog after it support multiple keys.
3. Revise data loading part in README.

### CODE REVIEW

**Comment by Colossus** [comment]
I'll start working on this

**Comment by Colossus** [comment]
@SenWu if I merge this into master, I see application.conf will not be overwritten. Is there a way to tell ./run.sh to use either app.ddlog or application.conf, should one of these not work?

**Comment by netj** [comment]
@Colossus `deepdive run` will run app.ddlog.  See http://deepdive.stanford.edu/doc/changelog/0.7.0-alpha.html and http://deepdive.stanford.edu/doc/advanced/deepdiveapp.html

(It seems some formatting errors came into the latest webpages.  Please ignore the `bash` in front of some commands.)

**Comment by Colossus** [comment]
Hey @SenWu after pulling and merging, I'm trying `deepdive run`, but it returns 

```
[error] app.ddlog[279.49] failure: `returns' expected but `g' found

function gene_extract_candidates over rows like gene_extract_candidates_input
```

This is almost certainly an error on my side (because I know you ran the thing at least once), but I don't know what I'm doing wrong. Could you help me out there?

**Comment by Colossus** [comment]
OKOK, sorry. Just pulled deepdive again and executed `make`. Continuing.

**Comment by senwu** [comment]
Did you run it with the latest version of Deepdive? The ddlog syntax has changed the format of function call rule (https://github.com/HazyResearch/ddlog/commit/8aeec0eaac22729661e65d42d0a31cfb136f8646).

**Comment by Colossus** [comment]
OK, now tripping on:

14:31:57 [extractorRunner-extraction_rule_14] ERROR org.postgresql.util.PSQLException: ERROR: relation "sentences_view" does not exist
  Position: 23
java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: relation "sentences_view" does not exist
  Position: 23
    at org.deepdive.extraction.ExtractorRunner.executeSqlUpdateOrFail(ExtractorRunner.scala:322) ~[deepdive.jar:0.7.0]
    at org.deepdive.extraction.ExtractorRunner$$anonfun$2.applyOrElse(ExtractorRunner.scala:143) ~[deepdive.jar:0.7.0]
    at org.deepdive.extraction.ExtractorRunner$$anonfun$2.applyOrElse(ExtractorRunner.scala:106) ~[deepdive.jar:0.7.0]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) ~[deepdive.jar:0.7.0]
    at akka.actor.FSM$class.processEvent(FSM.scala:587) ~[deepdive.jar:0.7.0]
    at org.deepdive.extraction.ExtractorRunner.processEvent(ExtractorRunner.scala:62) ~[deepdive.jar:0.7.0]
    at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:581) ~[deepdive.jar:0.7.0]
    at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:575) ~[deepdive.jar:0.7.0]
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[deepdive.jar:0.7.0]
    at org.deepdive.extraction.ExtractorRunner.aroundReceive(ExtractorRunner.scala:62) ~[deepdive.jar:0.7.0]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:491) [deepdive.jar:0.7.0]
    at akka.actor.ActorCell.invoke(ActorCell.scala:462) [deepdive.jar:0.7.0]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237) [deepdive.jar:0.7.0]
    at akka.dispatch.Mailbox.run(Mailbox.scala:219) [deepdive.jar:0.7.0]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) [deepdive.jar:0.7.0]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [deepdive.jar:0.7.0]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [deepdive.jar:0.7.0]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [deepdive.jar:0.7.0]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [deepdive.jar:0.7.0]

**Comment by Colossus** [comment]
@SenWu is sentences_view created somewhere? I don't see it in `schema.sql` or `input_schema.sql`.

**Comment by senwu** [comment]
Sentences_view is created by ddlog. See line 158 in app.ddlog

**Comment by Colossus** [comment]
Yeah but I'm just executing `deepdive run` and it's apparently not getting created. (?)

**Comment by senwu** [comment]
In ddlog, you just need run the following steps:
1. deepdive initdb
2. load sentence table
3. deepdive run

deepdive initdb will create all table mentioned ddlog.

**Comment by Colossus** [comment]
Oh shit. I'm sorry. Yeah I didn't do the first

**Comment by Colossus** [comment]
Oh man this is dropping sentences_input

**Comment by senwu** [comment]
In the original application.conf, data is loaded in sentences table and sentences_input is generated by a extractor from sentences table.

**Comment by Colossus** [comment]
well yeah but you can opt out. If I don't do preprocess, then I don't need the whole sentences table and can run directly from sentences_input if some data is there. And that's usually the case --- only @ajratner did the preprocessing once.

**Comment by senwu** [comment]
Sure, there is way to do this. you can run 'ddlog compile app.ddlog > deepdive.conf', modify the pipeline in deepdive.conf, and run 'deepdive run -c deepdive.conf' with modified config file.

I know it is a little bit tricky, but we can sync up with @netj to see whether there is a better way do this.

**Comment by Colossus** [comment]
OK thanks!

**Comment by senwu** [comment]
FYI: In order to run view, you need download the latest version minbender (https://github.com/HazyResearch/mindbender/releases) and set up the path, then
1. Populate the search index with the DeepDive data products.
   mindbender search update
2. Start the GUI
   mindbender search gui  

For more information, you can see the mindbender view example here: https://github.com/HazyResearch/mindbender/tree/master/examples/spouse_example

**Comment by Colossus** [comment]
In any case, since this is not interfering with application.conf, I'm going to merge this in right now.

**Pull request merged**
